### ISSUE TITLE
View-Edit-Submit after upload

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#41]
We should have the following set of features in our upload workflow:

- [x] Display cards with small info after inference for entries - #42 
- [x] Open Modal when clicking the View/Edit Button - #42 
- [x] Show detailed information when clicking V/E Button - #50 
- [x] Make Content editable in Modal - #52 
- [x] Make submit button work - #53 
- [x] Have a grey/green tick for every entry marking if it has been edited or viewed at least once - #54
