### ISSUE TITLE
List page

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#45]
This issue is to track progress for the page `/list`

- [x] List all forms | List forms in separate drawers by owning/not owning them - #47 
- [x] Clicking a card opens a modal that has a link to the form's page - #59 
- [x] Polish card details / looks - #83 

This thread can be used for ideas/suggestions
