### ISSUE TITLE
Form page

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#46]
This issue is to track the progress for the `/form` page

- [x] Displays information about a form
- [x] Shows a table with the data submitted for the form
- [x] Can export data to CSV / XLSX

Thread can be used for suggestions/ideas

**Comment by theodormoroianu** [comment]
We should use ag-grid, which has bindings for React:
https://www.ag-grid.com/example.php
